# Generated by Django 2.2.7 on 2019-11-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_twitters_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitters',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
