# Generated by Django 2.2.7 on 2019-12-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191130_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
